language: node_js

node_js:
  - '18'

cache:
  directories:
    - node_modules

before_install:
  - npm install -g npm@latest

script:
  - npm --version
  - npm config set progress false
  - npm install
  - npm run lint
  - npm test
  - npm run build
