-- CreateEnum
CREATE TYPE "ServiceCategory" AS ENUM ('TikTok', 'Instagram', 'Others');

-- CreateEnum
CREATE TYPE "ServiceType" AS ENUM ('Package', 'Service', 'CustomService', 'Account');

-- CreateEnum
CREATE TYPE "OrderStatus" AS ENUM ('Niezrealizowane', 'Zrealizowane');

-- CreateTable
CREATE TABLE "Service" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "description" STRING,
    "list" STRING[],
    "image" STRING,
    "price" DECIMAL(65,30) NOT NULL,
    "category" "ServiceCategory" NOT NULL,
    "type" "ServiceType" NOT NULL,
    "requireLink" STRING,

    CONSTRAINT "Service_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Customer" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "email" STRING NOT NULL,

    CONSTRAINT "Customer_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Order" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "email" STRING NOT NULL,
    "contents" STRING NOT NULL,
    "customerName" STRING NOT NULL,
    "status" "OrderStatus" NOT NULL,
    "customerId" INT4,
    "dateOfPurchase" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Order_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Customer_email_key" ON "Customer"("email");

-- AddForeignKey
ALTER TABLE "Order" ADD CONSTRAINT "Order_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE SET NULL ON UPDATE CASCADE;
