import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
 title: "Media Bliss",
 icons: { icon: "/logos/mb.png" },
 description: "Generated by create next app"
};

export default function RootLayout({
 children
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  <html lang="en">
   <head>
    <meta charSet="UTF-8" />
    <meta
     name="viewport"
     content="width=device-width, initial-scale=1.0"
    />
   </head>
   <body className={roboto.className}>{children}</body>
  </html>
 );
}
